feishu:
  # 该区域请于飞书开放平台查询本机器人信息,详见
  # https://open.feishu.cn/document/home/develop-a-bot-in-5-minutes/coding
  appId: cli_a591c1b02279900e
  appSecret: 
  verificationToken: 
  encryptKey: 
  larkHost: "https://open.feishu.cn"
server:
  # 端口，请根据实际情况为准
  port: 3000
  # add your custom fields here
  exampleField1: ExampleString
# add your custom fields here
departmentID: STD
# 可选值有：
#   department_id：以自定义department_id来标识部门
#   open_department_id：以open_department_id来标识部门
departmentIdType: department_id
# 填写需要使用机器人的用户open_id
whiteList:
